-- MySQL Script generated by MySQL Workbench
-- Thu Feb 16 00:10:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`foods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`foods` (
  `food_id` INT NOT NULL,
  `includesGMO` TINYINT NULL,
  PRIMARY KEY (`food_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`notfoods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`notfoods` (
  `notfood_id` INT NOT NULL,
  `warrantyPeriod` INT NULL,
  PRIMARY KEY (`notfood_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products` (
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10) NOT NULL,
  `currency` VARCHAR(45) NOT NULL,
  `exp_days` INT NULL,
  `notfood_notfood_id` INT NULL,
  `food_food_id` INT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_notfood1_idx` (`notfood_notfood_id` ASC) VISIBLE,
  INDEX `fk_products_food1_idx` (`food_food_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_notfood1`
    FOREIGN KEY (`notfood_notfood_id`)
    REFERENCES `shop`.`notfoods` (`notfood_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_food1`
    FOREIGN KEY (`food_food_id`)
    REFERENCES `shop`.`foods` (`food_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`buckets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`buckets` (
  `bucket_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `gk_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `bk`
    FOREIGN KEY (`bucket_id`)
    REFERENCES `shop`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gk`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`orders` (
  `orders_id` INT NOT NULL AUTO_INCREMENT,
  `processed` TINYINT NOT NULL,
  `date` DATE NOT NULL,
  `buckets_bucket_id` INT NOT NULL,
  PRIMARY KEY (`orders_id`),
  INDEX `bj_idx` (`buckets_bucket_id` ASC) VISIBLE,
  CONSTRAINT `bj`
    FOREIGN KEY (`buckets_bucket_id`)
    REFERENCES `shop`.`buckets` (`bucket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`order_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`order_info` (
  `idorder_info` INT NOT NULL AUTO_INCREMENT,
  `processed` TINYINT NOT NULL,
  `confirmed_date` DATE NULL,
  `created_date` DATE NOT NULL,
  `orders_orders_id` INT NULL,
  PRIMARY KEY (`idorder_info`),
  INDEX `fk_order_info_orders1_idx` (`orders_orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_info_orders1`
    FOREIGN KEY (`orders_orders_id`)
    REFERENCES `shop`.`orders` (`orders_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `shop`;

DELIMITER $$
USE `shop`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `orders_AFTER_INSERT` AFTER INSERT ON `orders` FOR EACH ROW BEGIN
INSERT INTO `shop`.`order_info`
(`orders_orders_id`, `processed`, `created_date`)
VALUES
(new.orders_id, 0 , current_date());
END$$

USE `shop`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `orders_AFTER_UPDATE` AFTER UPDATE ON `orders` FOR EACH ROW BEGIN
if new.processed = 1 then
UPDATE `shop`.`order_info`
SET `processed` = 1, `confirmed_date` = current_date() where new.orders_id = order_info.orders_orders_id;
END if;
end$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
